### ISSUE TITLE
Unity 5.4.0p4 problem

### ISSUE THREAD

**Issue by Arymond** [Perfare/UnityStudio#6]
(Reposted from the original branch)
Here are 2 files from Kamen Rider: Transcend Heroes (was Storm Heroes) (com.bandainamcoent.riderstorm) (Android)

Seems to be using 5.4.0 and don't open normally or extract correctly after cutting the headers.

https://www.dropbox.com/s/m87e5h5md5w3pq7/Character_EXA00.tmp?dl=0
Model: Cut off 0x5d (Textures (PVR) export fine, Model exporting Errors)

https://www.dropbox.com/s/n62tuxfrzjhr5qc/Voice_EXA.tmp?dl=0
Audio (FSB5) Cut off 0x87 (Exporting Assets give Blank Audio Files)

**Comment by Perfare** [comment]
Character_EXA00.tmp This file looks like it's broken.
Voice_EXA.tmp rename the extension from .tmp to .unity3d, extract work properly.

**Comment by Arymond** [comment]
thanks for the help with the sounds!
hmm not sure about the Models like i said i can pull the PVR just fine.

**Comment by Arymond** [comment]
if you'd like more samples for the models to get them to convert i can provide!

**Comment by Perfare** [comment]
Character_EXA00.tmp, This file is assetbundle, the first 0x5d bytes is a bundle header, this is necessary, but it's look like be broken or encrypted, can't convert or export at all

**Comment by Yuuyatails** [comment]
@Perfare: The error might related to the bones of the models.

Although the sound files and the texture files can be extracted with Unity Studio, the same does not applies to the 3d models itself.

It should be noted that the original 3d model assets files from that game were completely unrippable without editing them with the hex editor beforehand and is limited to _Kamen Rider: Transcend Heroes_ only. Another Bandai Namco game on smartphone, _Super Sentai: Legend Wars_, doesn't have this problem.

**Comment by Perfare** [comment]
@Yuuyatails Thanks for your explanation.

**Comment by Perfare** [comment]
I think this problem has been solved, if you have other questions, you can open the new issue

**Comment by Yuuyatails** [comment]
@Perfare: Sorry, but I have tested it and said problem hasn't been solved. It still creates 0 byte .fbx file.

**Comment by Perfare** [comment]
@Yuuyatails Really? I tested it export fsb file and convert to wav work properly.

**Comment by Yuuyatails** [comment]
@Perfare: That was for the audio assets files, not the 3d model assets.

**Comment by Perfare** [comment]
@Yuuyatails Sorry, my eyes are blurry. I think this file is corrupted or protected and it's not a mistake and don't need to solve it

**Comment by Yuuyatails** [comment]
@Perfare: Is the file corrupted? To me, the answer is a 'no' as I have said this in this thread before:

> It should be noted that the original 3d model assets files from that game were completely unrippable without editing them with the hex editor beforehand and is limited to _Kamen Rider: Transcend Heroes_ only. The game already have this kind of 'protection' to the 3d model files since the Unity version 4 days.

As of 2016, most of the current Unity games (on PC and smartphones) were using version 5.3.0 though 5.3.6.

Have you ever tried to extract models from other Unity games that are using version 5.4.0 and above? If not, you should put the 'Model export to FBX is not supported on asset file with version 5.4.0 and above' in the readme file, if fixing this problem is not on your priority list.

**Comment by Perfare** [comment]
@Yuuyatails Of course I've tested. I used Unity3d 5.4 to create a lot of files in order to test whether the Unity Studio is working properly. Here are some files you can download to test if you don't believe it
https://mega.nz/#!KVlRFZRI!Rpz_FIsCp5T6nzj-gcRoGmQ1rwWs0I0tj7OyNOjOnHA

I still say “Character_EXA00.tmp” is corrupted or encrypted. Because, this file must be a assetbundle file, but it has the wrong beginning bytes and the wrong end bytes, therefore it can be considered that some part of this file is also wrong(corrupted) and affect Unity Studio to export fbx file.

Unity Studio never guarantee that it will work properly in all games, so if some of the features in some games not working properly is normal, completely unnecessary to said "Unity Studio doesn't support exporting model to FBX on certain games"

**Comment by Yuuyatails** [comment]
@Perfare: 'Corrupted' is not the right word to explain this. 'Excrypted' would be the right one because I have tested the other 'Character_XXX00.tmp' files from the game and the result is always the same: Overflow error.

**Comment by Arymond** [comment]
https://www.dropbox.com/sh/5em54dc2qjs0lh1/AADsQ_GG0eGzhi7SEmSu4UjIa?dl=0

Here are samples from the older Version of the game when it worked. but you have to cut the header still
(i named them if you want to compare them to the Latest versions)

**Comment by Arymond** [comment]
https://i.gyazo.com/02459645e0c3b3d74beb7fb4a4c13270.png
If the File is Encrypted, how is unity Studio able to read the bones?
How am i able to Extract the Textures?
i have seen others rip the Models (With out rigging)
there has to be something wrong with this program.

**Comment by Yuuyatails** [comment]
@Arymond: Have you try to switch to the 'Asset list' tab? Select the textures in the list and select 'Selected Asset' to export the textures.

To tell you a truth, people are using Unity Asset Bundle Extractor (or UABE for short) to extract the 3d model's meshes _without_ bones and weight maps since Unity Studio is no longer able to extract the models from that game.

**Comment by Yuuyatails** [comment]
A update on this issue: With the commit dcde8902f1422ee775e90b5f1727d57048684801, Unity Studio can now extract 3d models from that game without any problem.

**Comment by Perfare** [comment]
@Yuuyatails Thank you for your tested
I made a mistake at that time, I'm sorry.
