### ISSUE TITLE
Mesh export problem

### ISSUE THREAD

**Issue by Sn0wBiT** [Perfare/UnityStudio#637]
This mesh asset have container: assets/prefabs/character/parts/y/p_f_0014.prefab. When export it is exported as .obj not .fbx and can't open. I don't know what wrong.

![Screenshot 2020-10-29 135907](https://user-images.githubusercontent.com/9019527/97535897-ef24a880-19ee-11eb-8abe-65fa5d8b009b.png)

**Comment by djm1176** [comment]
@Sn0wBiT It is possible that the filename is just incorrect in the export and you could try changing it to  `.fbx`. However it looks like in the image you sent that the data that is being exported is a prefab file, which is a text format to describe how a prefab was saved within the Unity project, rather than the 3D model itself. Try renaming to `*.prefab` and see if the file can be opened in a text editor

**Comment by Sn0wBiT** [comment]
File name is correct! But assets studio export as .obj file and I can't view that obj in any 3D model tools.
P/s: Preview tab in Assets studio can view model. But after export that file can't view.

**Comment by Perfare** [comment]
I think this error is impossible. If you want to fix this error, you can upload the source file to me.
