### ISSUE TITLE
CLR20r3 error on Windows 7

### ISSUE THREAD

**Issue by BreenBB** [Perfare/UnityStudio#661]
I downloaded Asset Studio but its not working, I got CLR20r3 error, although I installed Net Framework 4.7.2.

**Comment by KiruyaMomochi** [comment]
#607 #634 ?

**Comment by BreenBB** [comment]
On 607 link its says what it could be memory issue, I don't think its the case, I have both 64 bit version of windows and 12gb of ram. And program even didn't start.

**Comment by Perfare** [comment]
Can you describe in detail what happened when the error occurred?

**Comment by BreenBB** [comment]
Downloaded this program, and when I try open the AssetStudioGUI.exe I just got this error, program doesn't start.

**Comment by Poityu** [comment]
Hi,

I have a snapshot here if it helps:

![CRSH](https://user-images.githubusercontent.com/37011248/102351671-ccbc0e00-3fe1-11eb-998e-7884f15f9184.jpg)

This seems to be dependency/building issues.
My old copy of V 0.1438 is running fine. 

Hope this helps.

**Comment by Perfare** [comment]
@BreenBB @Poityu I need you to provide detailed error information to determine the cause of the error. In the Windows Event Viewer, view application events, you should see an error whose source is .NET Runtime, give me its details, thank you.

**Comment by Poityu** [comment]
Hi @Perfare,

As per request, here is the event log:

Application: AssetStudioGUI.exe 
Framework Version: v4.0.30319 
Description: The process was terminated due to an unhandled exception. 
Exception Info: System.ComponentModel.Win32Exception 
Exception Info: System.DllNotFoundException at AssetStudio.PInvoke.DllLoader+Win32.LoadDll(System.String, System.String) at AssetStudio.PInvoke.DllLoader.PreloadDll(System.String) at FMOD.Factory..cctor() 
Exception Info: System.TypeInitializationException at FMOD.Factory.System_Create(FMOD.System ByRef) at AssetStudioGUI.AssetStudioGUIForm.FMODinit() at AssetStudioGUI.AssetStudioGUIForm..ctor() at AssetStudioGUI.Program.Main() 

Regards~

**Comment by BreenBB** [comment]
Mine is here, its same as Poityu's: 
Приложение: AssetStudioGUI.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.ComponentModel.Win32Exception

Сведения об исключении: System.DllNotFoundException
   в AssetStudio.PInvoke.DllLoader+Win32.LoadDll(System.String, System.String)
   в AssetStudio.PInvoke.DllLoader.PreloadDll(System.String)
   в FMOD.Factory..cctor()

Сведения об исключении: System.TypeInitializationException
   в FMOD.Factory.System_Create(FMOD.System ByRef)
   в AssetStudioGUI.AssetStudioGUIForm.FMODinit()
   в AssetStudioGUI.AssetStudioGUIForm..ctor()
   в AssetStudioGUI.Program.Main()
 
And second one is:
Имя сбойного приложения: AssetStudioGUI.exe, версия: 0.15.23.0, отметка времени: 0xfbe9d864
Имя сбойного модуля: KERNELBASE.dll, версия: 6.1.7601.17514, отметка времени 0x4ce7c78c
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000000a49d
Идентификатор сбойного процесса: 0x12a4
Время запуска сбойного приложения: 0x01d6d4902f96ca3c
Путь сбойного приложения: C:\Tools\AssetStudio\AssetStudioGUI.exe
Путь сбойного модуля: C:\Windows\system32\KERNELBASE.dll
Код отчета: 6dcc93f8-4083-11eb-98fc-8cb07fdfce4e

Sorry about russian text, my Windows have russian localisation and Windows Event Viewer writes these like this.

**Comment by Perfare** [comment]
@Poityu @BreenBB This is a very strange situation. First, please use the 0.15.24 version, and then make sure that you unzip all the contents after downloading. Do not make any changes to the files and folders. Just start AssetStudioGUI.exe.

**Comment by BreenBB** [comment]
I tried 0.15.24 version, just unpacked and launched and still got same error:
Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	AssetStudioGUI.exe
  Сигнатура проблемы 02:	0.15.24.0
  Сигнатура проблемы 03:	f4bd24e0
  Сигнатура проблемы 04:	AssetStudioGUI
  Сигнатура проблемы 05:	0.15.24.0
  Сигнатура проблемы 06:	f4bd24e0
  Сигнатура проблемы 07:	1e0
  Сигнатура проблемы 08:	6
  Сигнатура проблемы 09:	System.TypeInitialization
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	6d06
  Дополнительные сведения 2:	6d064878d9ce0b4dbb4d03d66fa373ef
  Дополнительные сведения 3:	a4b7
  Дополнительные сведения 4:	a4b7fc1c20fb3e05f3842268031a22ad

**Comment by Poityu** [comment]
Hi @Perfare,

Eh, that would be a strange thing to do, no? (make changes to the files and folders, then run the app and expect it to work)

Are we back to square one? Will a special build (to be given to us) where you wrap the PreloadDll call in a try-catch statement and print out which Dll the app failed to load help? Otherwise I'm out of ideas. 
(A little digging around on stackoverflow gave me the impression that this log message doesn't necessary mean something is wrong with KERNELBASE.dll, hence the suggestion. I know only a little bit about programming, not enough to build the app from souce.)

**Comment by Poityu** [comment]
Hi @Perfare,

My last contribution here, as I really don't know anything else I can do.

I have toyed with my older copy, V.01438, and can confirm that the error log is a symptom of failing to locate fmod.dll, which is to say, for some reason, on our Win7 machines, V.01524 cannot find/load fmod.dll. 

As @BreenBB said, we did not make any changes to the file/folder structure, we extract, execute, and the app crashes.

**Comment by BreenBB** [comment]
> I have toyed with my older copy, V.01438

Interesting, do you still have V.01438? I want to check if it will work on my PC but I can't find how to download from appveyor site older version.

**Comment by Poityu** [comment]
> Interesting, do you still have V.01438? 

File sent.

> I can't find how to download from appveyor site older version.

Yes, appveyor only retains releases there for 6 months, after that, it is purged. So basically older versions are gone. I don't quite understand the choice to host releases there...

**Comment by BreenBB** [comment]
Thanks, this version is working, also I recently found this version its also works: https://github.com/War3zuk/Asset-Studio-x64

But its seems these old versions didn't fully support game which I wanted to open the assets, War3zuk version have support for versions 2.5 - 2019.1, while that game have 2019.4 or something like that version, its open assets files, and its possible to extract stuff, but its clearly what not all assets are loaded, this version supports versions from 2.5 - 2020.1, but sadly its not working.

**Comment by Poityu** [comment]
It would not make sense that branch by Wa3zuk would be able to handle the asset you want - it is even older than 0.1438.
> this version supports versions from 2.5 - 2020.1, but sadly its not working.

For now you'll have to borrow from someone who has a Win10. 
V 0.1524 runs fine on Win10.

**Comment by Poityu** [comment]
Hello @Perfare , 

It's been a long time. 

My old PC broke down a couple months ago. and now I'm running Win7 on another PC. 
I downloaded the current build 0.16, and it runs fine. 
So, whatever the problem was, faulty OS, broken framework installs, or the program itself?
(The broken PC was a Win7 SPECIAL edition that's been running for 6 years with messed up .NET registries which cannot be fixed even through reinstalls) 
we may never know, but I think it is ok to consider this issue closed. 

Thanks for the continued updates.
