### ISSUE TITLE
Program doesn't recognize .unity3d files containing skeletal mesh and animations. 

### ISSUE THREAD

**Issue by charlixzhao** [Perfare/UnityStudio#667]
When I try "load file" options, the program says "No file was loaded." When I try "extract file" option, the program also says "Finished extracting 0 files". I put the problematic files in the attachment. 
[Hero0.zip](https://github.com/Perfare/AssetStudio/files/5733713/Hero0.zip)

**Comment by 09williamsad** [comment]
The Unity files provided have leading hex/ascii data which prevents AssetStudio from seeing them as valid.

It starts with "tipsworksUnityFS......5.x.x.2018"
To be loaded the "tipsworks" part should be removed so the file starts with "UnityFS", then it loads.
![image](https://user-images.githubusercontent.com/23011550/103352821-30910d00-4a9f-11eb-8be1-200014dbe7d0.png)
[Hero0 fixed.zip](https://github.com/Perfare/AssetStudio/files/5754270/Hero0.fixed.zip)

**Comment by 09williamsad** [comment]
Additionally here is a powershell script I made a bit ago to fix this kind of issue.
[UnityFS file header fix.zip](https://github.com/Perfare/AssetStudio/files/5754317/UnityFS.file.header.fix.zip)

Edit it to change "$filesPath" variable to be where your files are stored then run it, it will then modify each file containing "UnityFS" so that "UnityFS" is the first thing in the file.

Backup your files first.
