### ISSUE TITLE
macOS/Linux Mono build?

### ISSUE THREAD

**Issue by DumbGameMaker** [Perfare/UnityStudio#696]
Is someone able to compile this with Mono to work on macOS or Linux?

**Comment by DumbGameMaker** [comment]
For those who were literally born yesterday and have been living under a rock ever since, Mono is a port of the .NET framework to macOS and Linux.

**Comment by piratesephiroth** [comment]
perhaps it can be moved to .NET Core

**Comment by KiruyaMomochi** [comment]
I have a .Net 5.0 fork for **the core** of this project: https://github.com/KiruyaMomochi/AssetStudioCore.
However, this does not work on macOS due to the lack of a header file.
To compile it yourself, you need to have CMake installed.

**Update**: Project updated, now use https://github.com/KiruyaMomochi/AssetStudio.

**Comment by Perfare** [comment]
You can consider using wine. 
Other components of AssetStudio can be directly modified to .net core/.net 5, but AssetStudioGUI is based on winform, even if it is modified to .net 5 platform, it cannot work on macOS/Linux.
