### ISSUE TITLE
The software is Taking much Ram

### ISSUE THREAD

**Issue by MAFIA-B0SS** [Perfare/UnityStudio#813]
![bandicam 2021-08-09 09-01-18-046](https://user-images.githubusercontent.com/39020530/128738479-2f3f6fde-3d4f-419b-bc05-4351ffce87ae.jpg)
The software is Taking much Ram
I have 6GB of ram and the software is taking about 93% of ram
normal ram usage is 35% Thank you

**Comment by max20091** [comment]
That's expected behavior since you load the entire game (or program data) into the extractor.
With a very well compressed game like this one, it can take as much as 8GB of RAM and beyond that from just about 1.5GB of compressed data.
![Untitled](https://user-images.githubusercontent.com/12845078/129191981-8e1024ed-318b-44c6-ac91-1f4bc2f4d7e9.png)
