### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by jasondyoungberg** [Perfare/UnityStudio#835]
I was trying to export a planet from the game outer wilds, but I get this error:
![image](https://user-images.githubusercontent.com/71162172/132111721-0baeb1d8-bab8-43fd-bcce-77eae09e6a37.png)

Steps to replicate:
1. Load `C:\Program Files (x86)\Steam\steamapps\common\Outer Wilds\OuterWilds_Data` folder
2. Select `level1/SolarSystemRoot/BrittleHollow_Body`
3. Model > Export selected objects (merge)

**Comment by jkerman2000** [comment]
I think it's because the assets you're trying to export contain non-model/animation data. Try going into the scene hierarchy and deselecting everything that isn't a model.

**Comment by Perfare** [comment]
Please upload the source file to me.

**Comment by jasondyoungberg** [comment]
The are 10GB of files, do you really need me to send them all, or can I just send some of them? Here is the folder tree: [tree.txt](https://github.com/Perfare/AssetStudio/files/7198836/tree.txt)

**Comment by jasondyoungberg** [comment]
@jkerman2000 That solution doesn't really work, since It is not very obvious which files are models or other stuff

**Comment by 09williamsad** [comment]
> 
> 
> Please upload the source file to me.

I have found this issue with a number of Outer Wilds's planets since an update, as it worked in the past.
I am not sure if sending over individual files over would work, as the game seems to use alot of shared assets and this occurs with multiple planets.
So here is the games _Data folder: https://mega.nz/file/bPBlxSjD#HJKP1zd4NVIpIQ3IM_PoygrXwbfEn1otAAxhcUncSCU
11GB compressed to 3.2GB.

AssetStudio version: 0.16.0
Outer Wilds version: 1.1.10
Unity version: 2019.4.27f1

"An item with the same key has already been added.":
level1\SolarSystemRoot\BrittleHollow_Body
level1\SolarSystemRoot\RingWorld_Body
level1\SolarSystemRoot\SunStation_Pivot
level1\SolarSystemRoot\StaticRing_Body
level1\SolarSystemRoot\FocalBody
level1\SolarSystemRoot\OrbitalProbeCannon_Pivot
level1\SolarSystemRoot\VolcanicMoon_Pivot
level1\SolarSystemRoot\TimberHearth_Body
level1\SolarSystemRoot\GiantsDeep_Body
![BrittleHollow_Body](https://user-images.githubusercontent.com/23011550/136707807-1d411d52-9a2f-49f5-bc5e-ad52cbf4226a.PNG)
![RingWorld_Body](https://user-images.githubusercontent.com/23011550/136707808-a0efe9ba-1c9f-495c-9667-21b52a1d9a87.PNG)

**Comment by 09williamsad** [comment]
I tried the base unupdated version of Outer Wilds, same problem.
I tried Asset studio v0.15.47, that worked fine.
This looks to be a problem with the v0.16.0 update.

**Comment by megalon** [comment]
I was having this issue trying to export Korra's model from Nickelodeon All-Star Brawl, and downgrading to `v0.15.47` fixed it for me.
