### ISSUE TITLE
Model size very small when extracted even after changing the scale size.

### ISSUE THREAD

**Issue by Lilothestitch16** [Perfare/UnityStudio#880]
When I export a model from a Unity Game, the model size is very small even when I change the scaling of them.

![image](https://user-images.githubusercontent.com/8963276/142924093-ae2afaa5-ab6d-455e-a213-e4d548d6abd5.png)

**Comment by johnwithlenon** [comment]
Just scale it up. I don't think this is an actual issue because the model is successful exported. I think it might fit well if you import the model into Unity. Your problem here is because of the different unit between different 3D modeling programs (Unity/Blender/MMD).
When I use blender to import models exported from AssetStudio, I usually need to scale it up x10 or x100.
You're using PMXEditor so there's a built-in plugin that can scale up the model (menu Edit > Plug-in > System > Size Change Tool). 
Btw, if you're using mmdtool plugin for blender to export to MMD model, make sure to read the last line in this page:
https://github.com/powroupi/blender_mmd_tools/wiki/1-MMD-unit-in-real-world-units

**Comment by Lilothestitch16** [comment]
I was using Noesis to convert the model to pmx

**Comment by Perfare** [comment]
In the export option, change the scale factor to 100.

**Comment by Lilothestitch16** [comment]
I changed the size in the options to 100 and exported the fbx to MMD from Noesis but the size is still small.

![image](https://user-images.githubusercontent.com/8963276/145716534-845868f9-0cab-4129-ba39-8c9536593a46.png)
![image](https://user-images.githubusercontent.com/8963276/145716665-0ec61d62-d2e8-4c3b-8e6c-4b3f5b15b827.png)
