### ISSUE TITLE
Digimon World Next Order

### ISSUE THREAD

**Issue by NickGurMatic69** [Perfare/UnityStudio#90]
https://mega.nz/#!gg51zJRZ!Fun6i33Jh0uipChlxldTr7b4JYyynviElch56vsv-ng The Digimon themselves have no skeleton it seems, however characters do, Not sure if this is an issue with unitystudio or just how the game does it. but I figure if it's possibly an issue with this then wynaut post aboot it.

**Comment by Yuuyatails** [comment]
First at all, are you sure that _Digimon World: Next Order_ was made with Unity? 

I ask you this because currently, there are no way to extract models from PS Vita properly, without facing any trouble. Oh and don't ever mention PS4, as no one has ever cracked its file system yet.

If you want the Digimon 3d models with bones so bad, you should extracts the models from the mobile game _Digimon Linkz_ (Also released by Bandai Namco Entertainment for iOS and Android) instead, as it was the only Digimon game that works perfect with Unity Studio so far.

**Comment by NickGurMatic69** [comment]
I am in fact, staring at the files, they are in fact, UnityRaw compressed 5.2.4f1, go ahead and open/decompress the file in UnityStudio. I wouldn't have posted this here if it weren't Unity. https://en.wikipedia.org/wiki/Digimon_World:_Next_Order  and I'm pretty sure there are digimon in here that aren't in linkz.

**Comment by Yuuyatails** [comment]
To @NickGurMatic69: I have, and the problem here is that both models has problem with textures and one of them has problem with bones.

You should understand that the current version of Unity Studio (Version 0.8.0) only supports Unity assets made for games on Web, Windows PC, Linux, MacOS, Xbox360, PS3, Android and iOS, as such, supports for assets PSVita and (if exist) PS4 are currently imcomplete. It will take a long while before the dev can bring in the PSVita assets support. Remember, we are talking about one single developer, not a team.

**Comment by Yuuyatails** [comment]
To @NickGurMatic69: I have, and one of them has problem with bones. However, It will take a long while before the dev can fix this. 

Remember, we are talking about one single developer, not a team.
